name: 'Main Workflow'
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: 'Build Workflow'
    runs-on: 'ubuntu-18.04'
    outputs:
      workflow_id: ${{ steps.compile.workflow_id }}
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v2'
      - id: 'compile'
        name: 'Compile hello.wdl'
        uses: 'jdidion/dxcompiler-compile-action@v2'
        with:
          wdl: 'hello.wdl'
          destination: 'project-XXX:/'
          api_token: '${{ secrets.API_TOKEN }}'
      - id: 'print'
        name: 'Print workflow'
        shell: 'bash'
        run: |
          echo "Workflow ID: ${{ steps.compile.outputs.workflow_id }}"
